name: spinifyapp

description: Spinify App Example

publish_to: 'none'

version: 1.0.0+1

homepage: https://centrifugal.dev

repository: https://github.com/PlugFox/spinify

issue_tracker: https://github.com/PlugFox/spinify/issues

funding:
  - https://www.buymeacoffee.com/plugfox
  - https://www.patreon.com/plugfox
  - https://boosty.to/plugfox

topics:
  - spinify
  - centrifugo
  - centrifuge
  - websocket
  - cross-platform

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:


environment:
  sdk: '>=3.1.0-63.1.beta <4.0.0'
  flutter: '>=3.10.1'


dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # Utils
  collection: any
  async: any
  meta: any
  path: any
  platform_info: ^4.0.2
  win32: ^5.0.6

  # Desktop
  window_manager: ^0.3.5

  # Logger
  l: ^4.0.2

  # Transport
  spinify:
    path: ../

  # UI
  cupertino_icons: ^1.0.2


dev_dependencies:
  # Unit & Widget tests for Flutter
  flutter_test:
    sdk: flutter
  # Integration tests for Flutter
  integration_test:
    sdk: flutter

  #mockito: ^5.4.2

  # Codegen
  build_runner: ^2.4.6
  #flutter_launcher_icons: ^0.13.1
  #flutter_native_splash: ^2.3.1
  # build_verify: ^3.1.0
  pubspec_generator: '>=4.0.0 <5.0.0'
  #flutter_gen_runner: ^5.3.1

  # Linting
  flutter_lints: ^2.0.1


flutter:
  generate: true
  uses-material-design: true


flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/common/localization
  output_dir: lib/src/common/localization/generated
  use_deferred_loading: false


#flutter_gen:
#  output: lib/src/common/constant/
#  line_length: 120