name: centrifuge_dart

description: >
  Dart client to communicate with Centrifuge and Centrifugo from Flutter and VM
  over WebSockets

version: 0.0.1-pre.1

homepage: https://centrifugal.dev

repository: https://github.com/PlugFox/centrifuge-client

issue_tracker: https://github.com/PlugFox/centrifuge-client/issues

funding:
  - https://www.buymeacoffee.com/plugfox
  - https://www.patreon.com/plugfox
  - https://boosty.to/plugfox

topics:
  - centrifugo
  - centrifuge
  - websocket
  - cross-platform
  - client

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

#screenshots:
#  - description: 'Example of using the ws library to connect to a Centrifugo server.'
#    path: example.png

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Annotations
  meta: ^1.9.1

  # WebSockets
  ws: ^1.0.0-pre.6

  # Protocol Buffers
  protobuf: ^3.0.0

  # Utilities
  crypto: ^3.0.3
  fixnum: ^1.1.0
  stack_trace: ^1.11.1

dev_dependencies:
  build_runner: ^2.4.6
  pubspec_generator: ^4.0.0
  lints: ^2.0.1
  test: ^1.24.2
