name: centrifuge_dart_example_console

description: >
  Dart client to communicate with Centrifuge and Centrifugo from Flutter and VM
  over WebSockets

version: 0.0.1-pre.1

publish_to: 'none'

homepage: https://centrifugal.dev

repository: https://github.com/PlugFox/centrifuge-client

issue_tracker: https://github.com/PlugFox/centrifuge-client/issues

funding:
  - https://www.buymeacoffee.com/plugfox
  - https://www.patreon.com/plugfox
  - https://boosty.to/plugfox

topics:
  - centrifugo
  - centrifuge
  - websocket
  - cross-platform
  - client

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

#screenshots:
#  - description: 'Example of using the ws library to connect to a Centrifugo server.'
#    path: example.png

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  centrifuge_dart:
    path: ../../

  args: ^2.4.2